[project]
name = "pyremdup"
version = "0.1.0"
description = "tool to change embedded subtitles"
authors = [{ name = "MadMcCrow", email = "do-not-mail.me@please.com" }]
requires-python = "~=3.11"
readme = "docs/README.md"
dependencies = [ ]

[project.scripts]
pyremdup = "pyremdup:main"