[project]
name = "gui"
version = "0.1.0"
requires-python = ">=3.11, <4"
dependencies = ["PySide6 >= 6.0.0", "nixos-pyinstall", "nixconfig"]

[tool.uv.sources]
nixconfig = {workspace = true}
nixos-pyinstall = { workspace = true }

[tool.uv]
package = true
