[project]
name = "nixconfig"
version = "0.1.0"
requires-python = ">=3.10, <4"
dependencies = ["pycall"]

[tool.uv.sources]
nixconfig = {workspace = true}
nixos-pyinstall = { workspace = true }

[tool.uv]
package = true
