[project]
name = "gui"
version = "0.1.0"
description = "Gui for pysubfixer"
requires-python = ">=3.11, <4"
dependencies = ["PySide6 >= 6.0.0", "ffmpy"]

[tool.uv]
package = true


[project.gui-scripts]
pysubfixer-gui = "gui:main"
